require('dotenv').config();
const express=require('express'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),Joi=require('joi'),cors=require('cors');
const app=express();app.use(cors());app.use(express.json());
let db;async function connect(){if(!process.env.MONGODB_URI)throw Error('MONGODB_URI is missing');return db||(db=mongoose.connect(process.env.MONGODB_URI,{serverSelectionTimeoutMS:10000}));}
const User=mongoose.models.User||mongoose.model('User',new mongoose.Schema({name:{type:String,required:true},email:{type:String,required:true,unique:true,lowercase:true},password:{type:String,required:true,select:false},role:{type:String,enum:['USER','ADMIN'],default:'USER'}},{timestamps:{createdAt:'date_created',updatedAt:'date_updated'},versionKey:false}));
const Toy=mongoose.models.Toy||mongoose.model('Toy',new mongoose.Schema({name:{type:String,required:true},info:{type:String,required:true},category:{type:String,required:true,lowercase:true},img_url:{type:String,default:''},price:{type:Number,required:true,min:0},user_id:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true}},{timestamps:{createdAt:'date_created',updatedAt:'date_updated'},versionKey:false}));
const validate=(s,where='body')=>(req,res,next)=>{const {value,error}=s.validate(req[where],{abortEarly:false,stripUnknown:true});if(error)return res.status(400).json({error:'Validation failed',details:error.details.map(x=>x.message)});req[where]=value;next()};
const auth=(req,res,next)=>{try{const t=req.header('x-api-key');if(!t)throw Error();req.user=jwt.verify(t,process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:'Invalid or missing token.'})}};
app.get('/',(req,res)=>res.json({name:'Toys API',status:'ok'}));app.use(async(req,res,next)=>{try{await connect();next()}catch(e){next(e)}});
const userSchema=Joi.object({name:Joi.string().min(2).max(60).required(),email:Joi.string().email().required(),password:Joi.string().min(8).required()});
app.post('/users',validate(userSchema),async(req,res,next)=>{try{const email=req.body.email.toLowerCase();if(await User.exists({email}))return res.status(409).json({error:'Email already exists.'});const user=await User.create({...req.body,email,password:await bcrypt.hash(req.body.password,12)});res.status(201).json({user:{id:user._id,name:user.name,email:user.email,role:user.role}})}catch(e){next(e)}});
app.post('/users/login',validate(Joi.object({email:Joi.string().email().required(),password:Joi.string().required()})),async(req,res,next)=>{try{const u=await User.findOne({email:req.body.email.toLowerCase()}).select('+password');if(!u||!(await bcrypt.compare(req.body.password,u.password)))return res.status(401).json({error:'Incorrect email or password.'});res.json({token:jwt.sign({sub:u._id.toString(),role:u.role},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||'7d'})})}catch(e){next(e)}});
const toySchema=Joi.object({name:Joi.string().min(2).max(80).required(),info:Joi.string().min(2).max(1000).required(),category:Joi.string().min(2).max(50).required(),img_url:Joi.string().uri().allow('').default(''),price:Joi.number().min(0).required()});const page=q=>({skip:Math.max(+q.skip||0,0),limit:10});const own=(t,u)=>t.user_id.toString()===u.sub||u.role==='ADMIN';
app.get('/toys',async(req,res,next)=>{try{const {skip,limit}=page(req.query),f={};if(req.query.s)f.$or=[{name:{$regex:req.query.s,$options:'i'}},{info:{$regex:req.query.s,$options:'i'}}];if(req.query.category)f.category=req.query.category.toLowerCase();const [items,total]=await Promise.all([Toy.find(f).skip(skip).limit(limit),Toy.countDocuments(f)]);res.json({items,pagination:{skip,limit,total}})}catch(e){next(e)}});app.get('/toys/count',async(req,res,next)=>{try{res.json({count:await Toy.countDocuments()})}catch(e){next(e)}});app.get('/toys/single/:id',async(req,res,next)=>{try{const x=await Toy.findById(req.params.id);x?res.json(x):res.status(404).json({error:'Toy not found.'})}catch(e){next(e)}});app.post('/toys',auth,validate(toySchema),async(req,res,next)=>{try{res.status(201).json(await Toy.create({...req.body,user_id:req.user.sub}))}catch(e){next(e)}});app.put('/toys/:id',auth,validate(toySchema),async(req,res,next)=>{try{const x=await Toy.findById(req.params.id);if(!x)return res.status(404).json({error:'Toy not found.'});if(!own(x,req.user))return res.status(403).json({error:'Forbidden'});Object.assign(x,req.body);await x.save();res.json(x)}catch(e){next(e)}});app.delete('/toys/:id',auth,async(req,res,next)=>{try{const x=await Toy.findById(req.params.id);if(!x)return res.status(404).json({error:'Toy not found.'});if(!own(x,req.user))return res.status(403).json({error:'Forbidden'});await x.deleteOne();res.status(204).send()}catch(e){next(e)}});
app.use((e,req,res,next)=>res.status(500).json({error:e.message||'Internal server error'}));if(require.main===module)connect().then(()=>app.listen(process.env.PORT||3001));module.exports=app;
